### PR TITLE
Task 4, Update code.c

### PR DESCRIPTION
**Pull request by Henryhin**
@tony1509 
A very simple C code, just notice me if there are any problem or suggestions. 🙇

### CODE REVIEW

**Comment by wongtc8** [comment]
I know there should be know conflicts, be just one thing:

> There are 5 items to be finished in the issues folder, please do them in the order #1 -> #2 -> #3 -> #4 -> #5 (team work)

So we should better commit finish task #2 and #3 (with issues posted), before merging this pull request.

**Comment by tony1509** [comment]
So we need to wait for one member's respond lol

**Comment by Henryhin** [comment]
No problem, I will hold this PR until task 2,3 done!
BTW I notice that the project board (step 1 of task 3) has already finished, 
but no one claim the credit and update the board regularly 😨

**Comment by tony1509** [comment]
And that stops our progress 😢

**Comment by tony1509** [comment]
Actually I suggest that we merge this already
Since travis-ci is silly and blocked every pull request Orz

**Pull request merged**
