### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RitoGamingPLZ**
Update Readme.md

### CODE REVIEW

**Comment by wongtc8** [comment]
Please open an issue before the PR (that's one of the requirements)

**Comment by wongtc8** [comment]
And also, remember this:
> assign another team member that can help you double check (but not @chuckjee or @wbwuta)

**Comment by wongtc8** [comment]
> And if you were to do Task 2, actually you have to include **ALL** students in _stu file if I didn't misunderstood the specification 😁

I think it's just required to do his/her __own__ (qutoed from [`/issues/task2.md`](/issues/task2.md))
> Under **Contributors**, use **`include_relative`** to include your own md file under the folder `_stu`

And after Task 2 is done, we should all add our own (quoted from [`/tasks.md`](/tasks.md))
> When Issue #2 is done, please check the **`readme.md`** file and add your own line in **Contributors**

**Comment by RitoGamingPLZ** [comment]
What does it mean by opening a issue before PR

**Comment by wongtc8** [comment]
> What does it mean by opening a issue before PR

Read the `tasks.md` carefully again, and you should know what to do! For you reference, I have done `issue-1` and this is the issue I opened before posting a Pull Request: [the opened issue for `issue-1`](https://github.com/csci3250-2019/project-team-f/issues/3)

**Pull request closed without merging**
