### PR TITLE
Create 1155108393.md

### PR DESCRIPTION
**Pull request by ericlikp**
add my name file to _stu folder

### CODE REVIEW

**Comment by tony1509** [comment]
I think you have to add '[ci-skip]' to avoid the silly ci check lol
I forgot that too :P

**Comment by Henryhin** [comment]
I just merged #19 PR, so you can re-build the Travis CI in both of your PR to get pass now.
sorry for any inconvenience caused .😞

**Comment by tony1509** [comment]
yay

**Comment by ericlikp** [comment]
> I think you have to add '[ci-skip]' to avoid the silly ci check lol
> I forgot that too :P

I dont get it XD
how? add to where

**Pull request merged**
